//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Demo_WebService.WebServiceReference {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://monte-bianco.com/", ConfigurationName="WebServiceReference.WebServiceSoap")]
    public interface WebServiceSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://monte-bianco.com/CheckSQLConnectionValid", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool CheckSQLConnectionValid(string SecurityCode, string ServerName, ref string ErrInfo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://monte-bianco.com/ExecuteSQLString_DataSet", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet ExecuteSQLString_DataSet(string SecurityCode, string ServerName, string SQLString, ref string ErrInfo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://monte-bianco.com/ExecuteStoredProcedure_DataSet", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet ExecuteStoredProcedure_DataSet(string SecurityCode, string ServerName, string ProcName, string ParmName_ParmDBType_ParmValue_ParmSize_ParmDirection, ref string ErrInfo);
        
        // CODEGEN: 参数“ExecuteStoredProcedure_DataSet_BinaryResult”需要其他方案信息，使用参数模式无法捕获这些信息。特定特性为“System.Xml.Serialization.XmlElementAttribute”。
        [System.ServiceModel.OperationContractAttribute(Action="http://monte-bianco.com/ExecuteStoredProcedure_DataSet_Binary", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Demo_WebService.WebServiceReference.ExecuteStoredProcedure_DataSet_BinaryResponse ExecuteStoredProcedure_DataSet_Binary(Demo_WebService.WebServiceReference.ExecuteStoredProcedure_DataSet_BinaryRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://monte-bianco.com/GetSQLServerDateTime", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string GetSQLServerDateTime(string StrSecurityCode, string StrServerName, ref string sErr);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://monte-bianco.com/ExecuteSQLString_DBPull", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool ExecuteSQLString_DBPull(string SecurityCode, string ServerName, string sSQL, string sTableName, ref System.Data.DataSet ds_Return, ref string sErr);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://monte-bianco.com/Execute_DBPush", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool Execute_DBPush(string SecurityCode, string ServerName, ref System.Data.DataSet ds_Return, ref string sErr);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://monte-bianco.com/ExecuteSQLStringBefore_DBPush", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool ExecuteSQLStringBefore_DBPush(string SecurityCode, string ServerName, string sExecuteSQL_BeforePush, ref System.Data.DataSet ds_ToPush, ref string sErr);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://monte-bianco.com/ExecuteSQLString_CheckRecordExists", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int ExecuteSQLString_CheckRecordExists(string SecurityCode, string ServerName, string SQLString, ref string sErr);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://monte-bianco.com/ExecuteSQLString", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool ExecuteSQLString(string SecurityCode, string ServerName, string SQLString, ref string sErr);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://monte-bianco.com/ExecuteStoredProcedure", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool ExecuteStoredProcedure(string SecurityCode, string ServerName, string sStoredProcedureName, string sParameters_DBType_Value_Size_Direction, ref string sErr);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://monte-bianco.com/ExecuteStoredProcedureWithOutPut_Int", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int ExecuteStoredProcedureWithOutPut_Int(string SecurityCode, string ServerName, string sStoredProcedureName, string sParameters_DBType_Value_Size_Direction, ref string sErr);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://monte-bianco.com/ExecuteStoredProcedureWithOutPut_String", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string ExecuteStoredProcedureWithOutPut_String(string SecurityCode, string ServerName, string sStoredProcedureName, string sParameters_DBType_Value_Size_Direction, ref string sErr);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://monte-bianco.com/ExecuteSQLString_String", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string ExecuteSQLString_String(string StrSecurityCode, string StrServerName, string SQLString, ref string sErr);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://monte-bianco.com/ExecuteSQLString_NoDelimiterString", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string ExecuteSQLString_NoDelimiterString(string StrSecurityCode, string StrServerName, string SQLString, ref string sErr);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://monte-bianco.com/ExecuteStoredProcedure_MultiString", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string ExecuteStoredProcedure_MultiString(string StrSecurityCode, string StrServerName, string SP, string sParameters_DBType_Value_Size_Direction, string SplitCode, ref string sErr);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://monte-bianco.com/ExecuteStoredProcedure_String", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string ExecuteStoredProcedure_String(string StrSecurityCode, string StrServerName, string SP, string sParameters_DBType_Value_Size_Direction, ref string sErr);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://monte-bianco.com/ExecuteStoredProcedure_NoDelimiterString", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string ExecuteStoredProcedure_NoDelimiterString(string StrSecurityCode, string StrServerName, string SP, string sParameters_DBType_Value_Size_Direction, ref string sErr);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://monte-bianco.com/StrToMd5", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string StrToMd5(string EnStr);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://monte-bianco.com/EncryptMD5", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string EncryptMD5(string sSourceStr, ref string sErr);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://monte-bianco.com/GetCurrentIP", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string GetCurrentIP(ref string sErr);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://monte-bianco.com/FileServer_FileExists", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool FileServer_FileExists(string StrSecurityCode, string StrServerName, string FileName, ref string errinfo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://monte-bianco.com/FileServer_DirectoryExists", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool FileServer_DirectoryExists(string StrSecurityCode, string StrServerName, string DirectoryName, ref string errinfo);
        
        // CODEGEN: 参数“Content”需要其他方案信息，使用参数模式无法捕获这些信息。特定特性为“System.Xml.Serialization.XmlElementAttribute”。
        [System.ServiceModel.OperationContractAttribute(Action="http://monte-bianco.com/FileServer_UploadFile", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Demo_WebService.WebServiceReference.FileServer_UploadFileResponse FileServer_UploadFile(Demo_WebService.WebServiceReference.FileServer_UploadFileRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://monte-bianco.com/FileServer_CreateDirectory", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool FileServer_CreateDirectory(string StrSecurityCode, string StrServerName, string DirectoryName, ref string errinfo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://monte-bianco.com/FileServer_DeleteDirectory", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool FileServer_DeleteDirectory(string StrSecurityCode, string StrServerName, string DirectoryName, ref string errinfo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://monte-bianco.com/FileServer_DeleteFile", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool FileServer_DeleteFile(string StrSecurityCode, string StrServerName, string FileName, ref string errinfo);
        
        // CODEGEN: 参数“FileServer_DownloadFileResult”需要其他方案信息，使用参数模式无法捕获这些信息。特定特性为“System.Xml.Serialization.XmlElementAttribute”。
        [System.ServiceModel.OperationContractAttribute(Action="http://monte-bianco.com/FileServer_DownloadFile", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Demo_WebService.WebServiceReference.FileServer_DownloadFileResponse FileServer_DownloadFile(Demo_WebService.WebServiceReference.FileServer_DownloadFileRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ExecuteStoredProcedure_DataSet_Binary", WrapperNamespace="http://monte-bianco.com/", IsWrapped=true)]
    public partial class ExecuteStoredProcedure_DataSet_BinaryRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://monte-bianco.com/", Order=0)]
        public string SecurityCode;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://monte-bianco.com/", Order=1)]
        public string ServerName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://monte-bianco.com/", Order=2)]
        public string ProcName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://monte-bianco.com/", Order=3)]
        public string ParmName_ParmDBType_ParmValue_ParmSize_ParmDirection;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://monte-bianco.com/", Order=4)]
        public string ErrInfo;
        
        public ExecuteStoredProcedure_DataSet_BinaryRequest() {
        }
        
        public ExecuteStoredProcedure_DataSet_BinaryRequest(string SecurityCode, string ServerName, string ProcName, string ParmName_ParmDBType_ParmValue_ParmSize_ParmDirection, string ErrInfo) {
            this.SecurityCode = SecurityCode;
            this.ServerName = ServerName;
            this.ProcName = ProcName;
            this.ParmName_ParmDBType_ParmValue_ParmSize_ParmDirection = ParmName_ParmDBType_ParmValue_ParmSize_ParmDirection;
            this.ErrInfo = ErrInfo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ExecuteStoredProcedure_DataSet_BinaryResponse", WrapperNamespace="http://monte-bianco.com/", IsWrapped=true)]
    public partial class ExecuteStoredProcedure_DataSet_BinaryResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://monte-bianco.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] ExecuteStoredProcedure_DataSet_BinaryResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://monte-bianco.com/", Order=1)]
        public string ErrInfo;
        
        public ExecuteStoredProcedure_DataSet_BinaryResponse() {
        }
        
        public ExecuteStoredProcedure_DataSet_BinaryResponse(byte[] ExecuteStoredProcedure_DataSet_BinaryResult, string ErrInfo) {
            this.ExecuteStoredProcedure_DataSet_BinaryResult = ExecuteStoredProcedure_DataSet_BinaryResult;
            this.ErrInfo = ErrInfo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="FileServer_UploadFile", WrapperNamespace="http://monte-bianco.com/", IsWrapped=true)]
    public partial class FileServer_UploadFileRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://monte-bianco.com/", Order=0)]
        public string StrSecurityCode;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://monte-bianco.com/", Order=1)]
        public string StrServerName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://monte-bianco.com/", Order=2)]
        public string FileName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://monte-bianco.com/", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] Content;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://monte-bianco.com/", Order=4)]
        public string errinfo;
        
        public FileServer_UploadFileRequest() {
        }
        
        public FileServer_UploadFileRequest(string StrSecurityCode, string StrServerName, string FileName, byte[] Content, string errinfo) {
            this.StrSecurityCode = StrSecurityCode;
            this.StrServerName = StrServerName;
            this.FileName = FileName;
            this.Content = Content;
            this.errinfo = errinfo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="FileServer_UploadFileResponse", WrapperNamespace="http://monte-bianco.com/", IsWrapped=true)]
    public partial class FileServer_UploadFileResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://monte-bianco.com/", Order=0)]
        public bool FileServer_UploadFileResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://monte-bianco.com/", Order=1)]
        public string errinfo;
        
        public FileServer_UploadFileResponse() {
        }
        
        public FileServer_UploadFileResponse(bool FileServer_UploadFileResult, string errinfo) {
            this.FileServer_UploadFileResult = FileServer_UploadFileResult;
            this.errinfo = errinfo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="FileServer_DownloadFile", WrapperNamespace="http://monte-bianco.com/", IsWrapped=true)]
    public partial class FileServer_DownloadFileRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://monte-bianco.com/", Order=0)]
        public string StrSecurityCode;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://monte-bianco.com/", Order=1)]
        public string StrServerName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://monte-bianco.com/", Order=2)]
        public string FileName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://monte-bianco.com/", Order=3)]
        public string errinfo;
        
        public FileServer_DownloadFileRequest() {
        }
        
        public FileServer_DownloadFileRequest(string StrSecurityCode, string StrServerName, string FileName, string errinfo) {
            this.StrSecurityCode = StrSecurityCode;
            this.StrServerName = StrServerName;
            this.FileName = FileName;
            this.errinfo = errinfo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="FileServer_DownloadFileResponse", WrapperNamespace="http://monte-bianco.com/", IsWrapped=true)]
    public partial class FileServer_DownloadFileResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://monte-bianco.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] FileServer_DownloadFileResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://monte-bianco.com/", Order=1)]
        public string errinfo;
        
        public FileServer_DownloadFileResponse() {
        }
        
        public FileServer_DownloadFileResponse(byte[] FileServer_DownloadFileResult, string errinfo) {
            this.FileServer_DownloadFileResult = FileServer_DownloadFileResult;
            this.errinfo = errinfo;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebServiceSoapChannel : Demo_WebService.WebServiceReference.WebServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebServiceSoapClient : System.ServiceModel.ClientBase<Demo_WebService.WebServiceReference.WebServiceSoap>, Demo_WebService.WebServiceReference.WebServiceSoap {
        
        public WebServiceSoapClient() {
        }
        
        public WebServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool CheckSQLConnectionValid(string SecurityCode, string ServerName, ref string ErrInfo) {
            return base.Channel.CheckSQLConnectionValid(SecurityCode, ServerName, ref ErrInfo);
        }
        
        public System.Data.DataSet ExecuteSQLString_DataSet(string SecurityCode, string ServerName, string SQLString, ref string ErrInfo) {
            return base.Channel.ExecuteSQLString_DataSet(SecurityCode, ServerName, SQLString, ref ErrInfo);
        }
        
        public System.Data.DataSet ExecuteStoredProcedure_DataSet(string SecurityCode, string ServerName, string ProcName, string ParmName_ParmDBType_ParmValue_ParmSize_ParmDirection, ref string ErrInfo) {
            return base.Channel.ExecuteStoredProcedure_DataSet(SecurityCode, ServerName, ProcName, ParmName_ParmDBType_ParmValue_ParmSize_ParmDirection, ref ErrInfo);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Demo_WebService.WebServiceReference.ExecuteStoredProcedure_DataSet_BinaryResponse Demo_WebService.WebServiceReference.WebServiceSoap.ExecuteStoredProcedure_DataSet_Binary(Demo_WebService.WebServiceReference.ExecuteStoredProcedure_DataSet_BinaryRequest request) {
            return base.Channel.ExecuteStoredProcedure_DataSet_Binary(request);
        }
        
        public byte[] ExecuteStoredProcedure_DataSet_Binary(string SecurityCode, string ServerName, string ProcName, string ParmName_ParmDBType_ParmValue_ParmSize_ParmDirection, ref string ErrInfo) {
            Demo_WebService.WebServiceReference.ExecuteStoredProcedure_DataSet_BinaryRequest inValue = new Demo_WebService.WebServiceReference.ExecuteStoredProcedure_DataSet_BinaryRequest();
            inValue.SecurityCode = SecurityCode;
            inValue.ServerName = ServerName;
            inValue.ProcName = ProcName;
            inValue.ParmName_ParmDBType_ParmValue_ParmSize_ParmDirection = ParmName_ParmDBType_ParmValue_ParmSize_ParmDirection;
            inValue.ErrInfo = ErrInfo;
            Demo_WebService.WebServiceReference.ExecuteStoredProcedure_DataSet_BinaryResponse retVal = ((Demo_WebService.WebServiceReference.WebServiceSoap)(this)).ExecuteStoredProcedure_DataSet_Binary(inValue);
            ErrInfo = retVal.ErrInfo;
            return retVal.ExecuteStoredProcedure_DataSet_BinaryResult;
        }
        
        public string GetSQLServerDateTime(string StrSecurityCode, string StrServerName, ref string sErr) {
            return base.Channel.GetSQLServerDateTime(StrSecurityCode, StrServerName, ref sErr);
        }
        
        public bool ExecuteSQLString_DBPull(string SecurityCode, string ServerName, string sSQL, string sTableName, ref System.Data.DataSet ds_Return, ref string sErr) {
            return base.Channel.ExecuteSQLString_DBPull(SecurityCode, ServerName, sSQL, sTableName, ref ds_Return, ref sErr);
        }
        
        public bool Execute_DBPush(string SecurityCode, string ServerName, ref System.Data.DataSet ds_Return, ref string sErr) {
            return base.Channel.Execute_DBPush(SecurityCode, ServerName, ref ds_Return, ref sErr);
        }
        
        public bool ExecuteSQLStringBefore_DBPush(string SecurityCode, string ServerName, string sExecuteSQL_BeforePush, ref System.Data.DataSet ds_ToPush, ref string sErr) {
            return base.Channel.ExecuteSQLStringBefore_DBPush(SecurityCode, ServerName, sExecuteSQL_BeforePush, ref ds_ToPush, ref sErr);
        }
        
        public int ExecuteSQLString_CheckRecordExists(string SecurityCode, string ServerName, string SQLString, ref string sErr) {
            return base.Channel.ExecuteSQLString_CheckRecordExists(SecurityCode, ServerName, SQLString, ref sErr);
        }
        
        public bool ExecuteSQLString(string SecurityCode, string ServerName, string SQLString, ref string sErr) {
            return base.Channel.ExecuteSQLString(SecurityCode, ServerName, SQLString, ref sErr);
        }
        
        public bool ExecuteStoredProcedure(string SecurityCode, string ServerName, string sStoredProcedureName, string sParameters_DBType_Value_Size_Direction, ref string sErr) {
            return base.Channel.ExecuteStoredProcedure(SecurityCode, ServerName, sStoredProcedureName, sParameters_DBType_Value_Size_Direction, ref sErr);
        }
        
        public int ExecuteStoredProcedureWithOutPut_Int(string SecurityCode, string ServerName, string sStoredProcedureName, string sParameters_DBType_Value_Size_Direction, ref string sErr) {
            return base.Channel.ExecuteStoredProcedureWithOutPut_Int(SecurityCode, ServerName, sStoredProcedureName, sParameters_DBType_Value_Size_Direction, ref sErr);
        }
        
        public string ExecuteStoredProcedureWithOutPut_String(string SecurityCode, string ServerName, string sStoredProcedureName, string sParameters_DBType_Value_Size_Direction, ref string sErr) {
            return base.Channel.ExecuteStoredProcedureWithOutPut_String(SecurityCode, ServerName, sStoredProcedureName, sParameters_DBType_Value_Size_Direction, ref sErr);
        }
        
        public string ExecuteSQLString_String(string StrSecurityCode, string StrServerName, string SQLString, ref string sErr) {
            return base.Channel.ExecuteSQLString_String(StrSecurityCode, StrServerName, SQLString, ref sErr);
        }
        
        public string ExecuteSQLString_NoDelimiterString(string StrSecurityCode, string StrServerName, string SQLString, ref string sErr) {
            return base.Channel.ExecuteSQLString_NoDelimiterString(StrSecurityCode, StrServerName, SQLString, ref sErr);
        }
        
        public string ExecuteStoredProcedure_MultiString(string StrSecurityCode, string StrServerName, string SP, string sParameters_DBType_Value_Size_Direction, string SplitCode, ref string sErr) {
            return base.Channel.ExecuteStoredProcedure_MultiString(StrSecurityCode, StrServerName, SP, sParameters_DBType_Value_Size_Direction, SplitCode, ref sErr);
        }
        
        public string ExecuteStoredProcedure_String(string StrSecurityCode, string StrServerName, string SP, string sParameters_DBType_Value_Size_Direction, ref string sErr) {
            return base.Channel.ExecuteStoredProcedure_String(StrSecurityCode, StrServerName, SP, sParameters_DBType_Value_Size_Direction, ref sErr);
        }
        
        public string ExecuteStoredProcedure_NoDelimiterString(string StrSecurityCode, string StrServerName, string SP, string sParameters_DBType_Value_Size_Direction, ref string sErr) {
            return base.Channel.ExecuteStoredProcedure_NoDelimiterString(StrSecurityCode, StrServerName, SP, sParameters_DBType_Value_Size_Direction, ref sErr);
        }
        
        public string StrToMd5(string EnStr) {
            return base.Channel.StrToMd5(EnStr);
        }
        
        public string EncryptMD5(string sSourceStr, ref string sErr) {
            return base.Channel.EncryptMD5(sSourceStr, ref sErr);
        }
        
        public string GetCurrentIP(ref string sErr) {
            return base.Channel.GetCurrentIP(ref sErr);
        }
        
        public bool FileServer_FileExists(string StrSecurityCode, string StrServerName, string FileName, ref string errinfo) {
            return base.Channel.FileServer_FileExists(StrSecurityCode, StrServerName, FileName, ref errinfo);
        }
        
        public bool FileServer_DirectoryExists(string StrSecurityCode, string StrServerName, string DirectoryName, ref string errinfo) {
            return base.Channel.FileServer_DirectoryExists(StrSecurityCode, StrServerName, DirectoryName, ref errinfo);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Demo_WebService.WebServiceReference.FileServer_UploadFileResponse Demo_WebService.WebServiceReference.WebServiceSoap.FileServer_UploadFile(Demo_WebService.WebServiceReference.FileServer_UploadFileRequest request) {
            return base.Channel.FileServer_UploadFile(request);
        }
        
        public bool FileServer_UploadFile(string StrSecurityCode, string StrServerName, string FileName, byte[] Content, ref string errinfo) {
            Demo_WebService.WebServiceReference.FileServer_UploadFileRequest inValue = new Demo_WebService.WebServiceReference.FileServer_UploadFileRequest();
            inValue.StrSecurityCode = StrSecurityCode;
            inValue.StrServerName = StrServerName;
            inValue.FileName = FileName;
            inValue.Content = Content;
            inValue.errinfo = errinfo;
            Demo_WebService.WebServiceReference.FileServer_UploadFileResponse retVal = ((Demo_WebService.WebServiceReference.WebServiceSoap)(this)).FileServer_UploadFile(inValue);
            errinfo = retVal.errinfo;
            return retVal.FileServer_UploadFileResult;
        }
        
        public bool FileServer_CreateDirectory(string StrSecurityCode, string StrServerName, string DirectoryName, ref string errinfo) {
            return base.Channel.FileServer_CreateDirectory(StrSecurityCode, StrServerName, DirectoryName, ref errinfo);
        }
        
        public bool FileServer_DeleteDirectory(string StrSecurityCode, string StrServerName, string DirectoryName, ref string errinfo) {
            return base.Channel.FileServer_DeleteDirectory(StrSecurityCode, StrServerName, DirectoryName, ref errinfo);
        }
        
        public bool FileServer_DeleteFile(string StrSecurityCode, string StrServerName, string FileName, ref string errinfo) {
            return base.Channel.FileServer_DeleteFile(StrSecurityCode, StrServerName, FileName, ref errinfo);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Demo_WebService.WebServiceReference.FileServer_DownloadFileResponse Demo_WebService.WebServiceReference.WebServiceSoap.FileServer_DownloadFile(Demo_WebService.WebServiceReference.FileServer_DownloadFileRequest request) {
            return base.Channel.FileServer_DownloadFile(request);
        }
        
        public byte[] FileServer_DownloadFile(string StrSecurityCode, string StrServerName, string FileName, ref string errinfo) {
            Demo_WebService.WebServiceReference.FileServer_DownloadFileRequest inValue = new Demo_WebService.WebServiceReference.FileServer_DownloadFileRequest();
            inValue.StrSecurityCode = StrSecurityCode;
            inValue.StrServerName = StrServerName;
            inValue.FileName = FileName;
            inValue.errinfo = errinfo;
            Demo_WebService.WebServiceReference.FileServer_DownloadFileResponse retVal = ((Demo_WebService.WebServiceReference.WebServiceSoap)(this)).FileServer_DownloadFile(inValue);
            errinfo = retVal.errinfo;
            return retVal.FileServer_DownloadFileResult;
        }
    }
}
