//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Demo_WebService.SRMWebService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://wmsKd.server.cxf.srm/", ConfigurationName="SRMWebService.WSForWmsKdI")]
    public interface WSForWmsKdI {
        
        // CODEGEN: 参数“return”需要其他方案信息，使用参数模式无法捕获这些信息。特定特性为“System.Xml.Serialization.XmlElementAttribute”。
        [System.ServiceModel.OperationContractAttribute(Action="http://wmsKd.server.cxf.srm/WSForWmsKdI/getWmsRequest", ReplyAction="http://wmsKd.server.cxf.srm/WSForWmsKdI/getWmsResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        Demo_WebService.SRMWebService.getWmsResponse getWms(Demo_WebService.SRMWebService.getWmsRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://wmsKd.server.cxf.srm/")]
    public partial class requWmsReqList : object, System.ComponentModel.INotifyPropertyChanged {
        
        private requWmsBody[] requListField;
        
        private requWmsHead requWmsHeadField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("requList", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=0)]
        public requWmsBody[] requList {
            get {
                return this.requListField;
            }
            set {
                this.requListField = value;
                this.RaisePropertyChanged("requList");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public requWmsHead requWmsHead {
            get {
                return this.requWmsHeadField;
            }
            set {
                this.requWmsHeadField = value;
                this.RaisePropertyChanged("requWmsHead");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://wmsKd.server.cxf.srm/")]
    public partial class requWmsBody : object, System.ComponentModel.INotifyPropertyChanged {
        
        private double rTVquantityField;
        
        private bool rTVquantityFieldSpecified;
        
        private int sRMLineNoField;
        
        private bool sRMLineNoFieldSpecified;
        
        private string dateField;
        
        private string extend1Field;
        
        private string extend2Field;
        
        private string extend3Field;
        
        private string extend4Field;
        
        private string extend5Field;
        
        private string extend6Field;
        
        private string itemCodeField;
        
        private double qualifiedQtyField;
        
        private bool qualifiedQtyFieldSpecified;
        
        private double quantityField;
        
        private bool quantityFieldSpecified;
        
        private double scrapquantityField;
        
        private bool scrapquantityFieldSpecified;
        
        private string statusField;
        
        private string unitField;
        
        private string unqualifiedResultField;
        
        private string unqualifiedTypeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public double RTVquantity {
            get {
                return this.rTVquantityField;
            }
            set {
                this.rTVquantityField = value;
                this.RaisePropertyChanged("RTVquantity");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool RTVquantitySpecified {
            get {
                return this.rTVquantityFieldSpecified;
            }
            set {
                this.rTVquantityFieldSpecified = value;
                this.RaisePropertyChanged("RTVquantitySpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int SRMLineNo {
            get {
                return this.sRMLineNoField;
            }
            set {
                this.sRMLineNoField = value;
                this.RaisePropertyChanged("SRMLineNo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool SRMLineNoSpecified {
            get {
                return this.sRMLineNoFieldSpecified;
            }
            set {
                this.sRMLineNoFieldSpecified = value;
                this.RaisePropertyChanged("SRMLineNoSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string date {
            get {
                return this.dateField;
            }
            set {
                this.dateField = value;
                this.RaisePropertyChanged("date");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string extend1 {
            get {
                return this.extend1Field;
            }
            set {
                this.extend1Field = value;
                this.RaisePropertyChanged("extend1");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string extend2 {
            get {
                return this.extend2Field;
            }
            set {
                this.extend2Field = value;
                this.RaisePropertyChanged("extend2");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string extend3 {
            get {
                return this.extend3Field;
            }
            set {
                this.extend3Field = value;
                this.RaisePropertyChanged("extend3");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string extend4 {
            get {
                return this.extend4Field;
            }
            set {
                this.extend4Field = value;
                this.RaisePropertyChanged("extend4");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string extend5 {
            get {
                return this.extend5Field;
            }
            set {
                this.extend5Field = value;
                this.RaisePropertyChanged("extend5");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string extend6 {
            get {
                return this.extend6Field;
            }
            set {
                this.extend6Field = value;
                this.RaisePropertyChanged("extend6");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public string itemCode {
            get {
                return this.itemCodeField;
            }
            set {
                this.itemCodeField = value;
                this.RaisePropertyChanged("itemCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public double qualifiedQty {
            get {
                return this.qualifiedQtyField;
            }
            set {
                this.qualifiedQtyField = value;
                this.RaisePropertyChanged("qualifiedQty");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool qualifiedQtySpecified {
            get {
                return this.qualifiedQtyFieldSpecified;
            }
            set {
                this.qualifiedQtyFieldSpecified = value;
                this.RaisePropertyChanged("qualifiedQtySpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=11)]
        public double quantity {
            get {
                return this.quantityField;
            }
            set {
                this.quantityField = value;
                this.RaisePropertyChanged("quantity");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool quantitySpecified {
            get {
                return this.quantityFieldSpecified;
            }
            set {
                this.quantityFieldSpecified = value;
                this.RaisePropertyChanged("quantitySpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=12)]
        public double scrapquantity {
            get {
                return this.scrapquantityField;
            }
            set {
                this.scrapquantityField = value;
                this.RaisePropertyChanged("scrapquantity");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool scrapquantitySpecified {
            get {
                return this.scrapquantityFieldSpecified;
            }
            set {
                this.scrapquantityFieldSpecified = value;
                this.RaisePropertyChanged("scrapquantitySpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=13)]
        public string status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
                this.RaisePropertyChanged("status");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=14)]
        public string unit {
            get {
                return this.unitField;
            }
            set {
                this.unitField = value;
                this.RaisePropertyChanged("unit");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=15)]
        public string unqualifiedResult {
            get {
                return this.unqualifiedResultField;
            }
            set {
                this.unqualifiedResultField = value;
                this.RaisePropertyChanged("unqualifiedResult");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=16)]
        public string unqualifiedType {
            get {
                return this.unqualifiedTypeField;
            }
            set {
                this.unqualifiedTypeField = value;
                this.RaisePropertyChanged("unqualifiedType");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://wmsKd.server.cxf.srm/")]
    public partial class requWmsHead : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string codeField;
        
        private string extend1Field;
        
        private string extend2Field;
        
        private string extend3Field;
        
        private string extend4Field;
        
        private string extend5Field;
        
        private string extend6Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
                this.RaisePropertyChanged("code");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string extend1 {
            get {
                return this.extend1Field;
            }
            set {
                this.extend1Field = value;
                this.RaisePropertyChanged("extend1");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string extend2 {
            get {
                return this.extend2Field;
            }
            set {
                this.extend2Field = value;
                this.RaisePropertyChanged("extend2");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string extend3 {
            get {
                return this.extend3Field;
            }
            set {
                this.extend3Field = value;
                this.RaisePropertyChanged("extend3");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string extend4 {
            get {
                return this.extend4Field;
            }
            set {
                this.extend4Field = value;
                this.RaisePropertyChanged("extend4");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string extend5 {
            get {
                return this.extend5Field;
            }
            set {
                this.extend5Field = value;
                this.RaisePropertyChanged("extend5");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string extend6 {
            get {
                return this.extend6Field;
            }
            set {
                this.extend6Field = value;
                this.RaisePropertyChanged("extend6");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getWms", WrapperNamespace="http://wmsKd.server.cxf.srm/", IsWrapped=true)]
    public partial class getWmsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://wmsKd.server.cxf.srm/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Demo_WebService.SRMWebService.requWmsReqList requWmsReqList;
        
        public getWmsRequest() {
        }
        
        public getWmsRequest(Demo_WebService.SRMWebService.requWmsReqList requWmsReqList) {
            this.requWmsReqList = requWmsReqList;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getWmsResponse", WrapperNamespace="http://wmsKd.server.cxf.srm/", IsWrapped=true)]
    public partial class getWmsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://wmsKd.server.cxf.srm/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string @return;
        
        public getWmsResponse() {
        }
        
        public getWmsResponse(string @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WSForWmsKdIChannel : Demo_WebService.SRMWebService.WSForWmsKdI, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WSForWmsKdIClient : System.ServiceModel.ClientBase<Demo_WebService.SRMWebService.WSForWmsKdI>, Demo_WebService.SRMWebService.WSForWmsKdI {
        
        public WSForWmsKdIClient() {
        }
        
        public WSForWmsKdIClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WSForWmsKdIClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WSForWmsKdIClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WSForWmsKdIClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Demo_WebService.SRMWebService.getWmsResponse Demo_WebService.SRMWebService.WSForWmsKdI.getWms(Demo_WebService.SRMWebService.getWmsRequest request) {
            return base.Channel.getWms(request);
        }
        
        public string getWms(Demo_WebService.SRMWebService.requWmsReqList requWmsReqList) {
            Demo_WebService.SRMWebService.getWmsRequest inValue = new Demo_WebService.SRMWebService.getWmsRequest();
            inValue.requWmsReqList = requWmsReqList;
            Demo_WebService.SRMWebService.getWmsResponse retVal = ((Demo_WebService.SRMWebService.WSForWmsKdI)(this)).getWms(inValue);
            return retVal.@return;
        }
    }
}
